.include "macro.inc"

.section .rodata

/* Generated by spimdisasm 1.10.1 */

glabel D_800716C0
/* 722C0 800716C0 4075E00000000000 */ .double 350

glabel D_800716C8
/* 722C8 800716C8 4082C00000000000 */ .double 600
