.include "macro.inc"

.section .rodata

/* Generated by spimdisasm 1.10.1 */

glabel D_80072320
/* 72F20 80072320 3F8012EF */ .float 1.000577807

glabel D_80072324
/* 72F24 80072324 3F7FDA28 */ .float 0.9994225502
/* 72F28 80072328 00000000 */ .float 0
/* 72F2C 8007232C 00000000 */ .float 0
