.include "macro.inc"

.section .rodata

/* Generated by spimdisasm 1.10.1 */

glabel D_80071E50
/* 72A50 80071E50 412E848000000000 */ .double 1000000

glabel D_80071E58
/* 72A58 80071E58 412E848000000000 */ .double 1000000
