.include "macro.inc"

.section .rodata

/* Generated by spimdisasm 1.10.1 */

glabel D_80071F10
/* 72B10 80071F10 7F810000 */ .word 0x7F810000
/* 72B14 80071F14 00000000 */ .float 0
/* 72B18 80071F18 00000000 */ .float 0
/* 72B1C 80071F1C 00000000 */ .float 0
