.include "macro.inc"

.section .rodata

/* Generated by spimdisasm 1.10.1 */

glabel D_80071B90
/* 72790 80071B90 3F91DF469D353918 */ .double 0.017453292222222222
/* 72798 80071B98 00000000 */ .double 0
