.include "macro.inc"

.section .rodata

/* Generated by spimdisasm 1.10.1 */

glabel D_800723C0
/* 72FC0 800723C0 412E848000000000 */ .double 1000000

glabel D_800723C8
/* 72FC8 800723C8 412E848000000000 */ .double 1000000
