.include "macro.inc"

.section .rodata

/* Generated by spimdisasm 1.10.1 */

glabel D_80071C00
/* 72800 80071C00 412E848000000000 */ .double 1000000

glabel D_80071C08
/* 72808 80071C08 412E848000000000 */ .double 1000000
